Dmcs\NotesManagerBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Dmcs\NotesManagerBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
