security:
    encoders:
        Dmcs\NotesManagerBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    providers:
        main:
            entity: { class: DmcsNotesManagerBundle:User, property: username }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: /login$
            security: false

        main:
            pattern: ^/
            anonymous: ~
            security: true
            form_login:
                login_path: /login
                check_path: /login_check
                post_only: true
                default_target_path: /home
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/home, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
