security:
    providers:
        user_db:
            entity: { class: Dmcs\NotesManagerBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~

        secured_area:
            pattern: ^/
            anonymous: ~
            form_login: ~

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12