dmcs_notes_manager_homepage:
    path:     /
    defaults: { _controller: DmcsNotesManagerBundle:Default:index }
    methods: [GET]

home_path:
    path: /home/
    defaults: { _controller: DmcsNotesManagerBundle:Home:index }

new_note_path:
    path: /home/new-note
    defaults: { _controller: DmcsNotesManagerBundle:Home:newNote }

note_delete_path:
    path: /home/delete-note/{noteId}
    defaults: { _controller: DmcsNotesManagerBundle:Home:deleteNote }

new_category_path:
    path: /home/new-category
    defaults: { _controller: DmcsNotesManagerBundle:Home:newCategory }

show_note_path:
    path: /home/notes/{noteId}
    defaults: { _controller: DmcsNotesManagerBundle:Home:showNote }

register_path:
    path: /register
    defaults: { _controller: DmcsNotesManagerBundle:Auth:register }
    methods: [POST]

api_main:
    path: /api/{method}
    defaults: { _controller: DmcsNotesManagerBundle:Api:route, method: index }
    methods: [POST]

login:
    path: /login
    defaults: { _controller: DmcsNotesManagerBundle:Auth:login }

login_check:
    path: /login_check

logout:
    path: /logout